require 'spec_helper'

describe 'yum::base' do

  context 'yum::base uses default attributes' do
    let(:chef_run) { ChefSpec::Runner.new( step_into: ['yum_repository']).converge(described_recipe) }
    
    # Make sure base recipe removes default configurations. We will
    # recreate their contents over multiple files later.
    it 'deletes yum_repository[CentOS-Base]' do
      expect(chef_run).to delete_yum_repository('CentOS-Base')
    end
    
    # Make sure the yum_repository delete action works properly
    it 'steps into yum_repository and deletes file /etc/yum.repos.d/CentOS-Base.repo' do
      expect(chef_run).to delete_file('/etc/yum.repos.d/CentOS-Base.repo')
    end
    
    it 'deletes yum_repository[CentOS-Debuginfo]' do
      expect(chef_run).to delete_yum_repository('CentOS-Debuginfo')
    end
    
    it 'deletes yum_repository[CentOS-Media]' do
      expect(chef_run).to delete_yum_repository('CentOS-Media')
    end
    
    it 'deletes yum_repository[CentOS-Vault]' do
      expect(chef_run).to delete_yum_repository('CentOS-Vault')
    end
    
    # break repositoryid sections into yum_repositories
    it 'creates yum_repository[base]' do
      expect(chef_run).to create_yum_repository('base')
    end
    
    it 'creates yum_repository[updates]' do
      expect(chef_run).to create_yum_repository('updates')
    end
    
    it 'creates yum_repository[extras]' do
      expect(chef_run).to create_yum_repository('extras')
    end
    
    it 'creates yum_repository[centosplus]' do
      expect(chef_run).to create_yum_repository('centosplus')
    end
    
    it 'creates yum_repository[contrib]' do
      expect(chef_run).to create_yum_repository('contrib')
    end

    let(:content) {
      '# Generated by Chef
# Local modifications will be overwritten.

[base]
name=CentOS-$releasever - Base
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
sslverify=1
'
    }
    
    it 'steps into yum_repository and creates file /etc/yum.repos.d/base.repo' do
      expect(chef_run).to render_file('/etc/yum.repos.d/base.repo').with_content(content)
    end
  end
    
  context 'sets yum.base.cost' do
    let(:base_chef_run) { ChefSpec::Runner.new( step_into: ['yum_repository']) }
    let(:mycontent) {
      '# Generated by Chef
# Local modifications will be overwritten.

[base]
name=CentOS-$releasever - Base
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
sslverify=1
cost=42
'
    }
    it 'steps into yum_repository and creates file /etc/yum.repos.d/base.repo' do
      base_chef_run.node.override['yum']['base']['cost'] = 42
      base_chef_run.converge(described_recipe)
      expect(base_chef_run).to render_file('/etc/yum.repos.d/base.repo').with_content(mycontent)
    end
    
  end
end

# it "renders minimal configs" do
#   centos6_run.node.default['yum']['base']['repositoryid'] = 'base'
#   centos6_run.node.default['yum']['base']['description'] = 'CentOS-$releasever - Base'
#   centos6_run.node.default['yum']['base']['baseurl'] = 'http://mirror.centos.org/centos/$releasever/os/$basearch/'
#   centos6_run.node.default['yum']['base']['mirrorlist'] = 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os'
#   centos6_run.node.default['yum']['base']['gpgcheck'] = true
#   centos6_run.node.default['yum']['base']['gpgkey'] = 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6'
#   centos6_run.node.default['yum']['base']['enabled'] = true
#   centos6_run.node.default['yum']['base']['cost'] = nil
#   centos6_run.node.default['yum']['base']['exclude'] = nil
#   centos6_run.node.default['yum']['base']['enablegroups'] = nil
#   centos6_run.node.default['yum']['base']['failovermethod'] = nil
#   centos6_run.node.default['yum']['base']['http_caching'] = nil
#   centos6_run.node.default['yum']['base']['include_config'] = nil
#   centos6_run.node.default['yum']['base']['includepkgs'] = nil
#   centos6_run.node.default['yum']['base']['keepalive'] = nil
#   centos6_run.node.default['yum']['base']['max_retries'] = nil
#   centos6_run.node.default['yum']['base']['metadata_expire'] = nil
#   centos6_run.node.default['yum']['base']['priority'] = nil
#   centos6_run.node.default['yum']['base']['proxy'] = nil
#   centos6_run.node.default['yum']['base']['proxy_username'] = nil
#   centos6_run.node.default['yum']['base']['proxy_password'] = nil
#   centos6_run.node.default['yum']['base']['sslcacert'] = nil
#   centos6_run.node.default['yum']['base']['sslclientcert'] = nil
#   centos6_run.node.default['yum']['base']['sslclientkey'] = nil
#   centos6_run.node.default['yum']['base']['sslverify'] = nil
#   centos6_run.node.default['yum']['base']['timeout'] = nil
# end
